### ISSUE TITLE
two errors when smartpanty enabled

### ISSUE THREAD

**Issue by ghost** [habari-extras/habarimarkdown#2]
first error:
`Warning: require_once(php-smartypants/smartypants.php): failed to open stream: No such file or directory in user\plugins\habarimarkdown\habarimarkdown.plugin.php line 18`
solution: add subfolder Michelf/

second error:
`Error: Call to undefined function SmartyPants() in user\plugins\habarimarkdown\habarimarkdown.plugin.php line 97`
i'am not a programmer and so i have no solution, whats wrong?

**Comment by miklb** [comment]
Sounds like you may have cloned the repo and failed to initialize the submodules.
